[build]
builder = "dockerfile"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
healthcheckPath = "/"
healthcheckInterval = 30
healthcheckTimeout = 10
healthcheckStartPeriod = 60
